version: '3.9'

services:
  backend:
    build: .
    container_name: practice-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./app:/app  

  redis:
    image: redis:7
    container_name: practice-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: practice-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
